apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindlab-deployment
  labels:
    app: kindlab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kindlab
  template:
    metadata:
      labels:
        app: kindlab
    spec:
      containers:
      - name: kindlab
        image: localhost:5000/kindlab:latest
        ports:
        - containerPort: 3300